version: '3.3'

services:

  db:
    build:
      context: ../docker/db
      dockerfile: ./Dockerfile

  web:
    build:
      context: ../
      dockerfile: ./docker/web/Dockerfile

  save-handler:
    build:
      context: ../
      dockerfile: ./docker/save-handler/Dockerfile

  index-handler:
    build:
      context: ../
      dockerfile: ./docker/index-handler/Dockerfile