version: '3.3'

services:

  db:
    ports:    
      - "1433"
    environment: 
      - PASSWORD_PATH=C:\fake-secrets\sapassword.txt
    volumes:
      - .\fake-secrets:C:\fake-secrets

  web:
    ports:
      - "80"
    environment: 
      - DB_CONNECTION_STRING_PATH=C:\fake-secrets\connectionstring.txt
    volumes:
      - .\fake-secrets:C:\fake-secrets
      
  save-handler:
    environment: 
      - DB_CONNECTION_STRING_PATH=C:\fake-secrets\connectionstring.txt
    volumes:
      - .\fake-secrets:C:\fake-secrets
  
  kibana:
    ports:
      - "5601"

networks:
  app-net:
    external:
      name: nat