version: '3.3'
services:
  proxy:
    image: dockercloud/haproxy
    depends_on:
      - tomcat
    environment:
      - BALANCE=leastconn
      - MODE=http
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
    networks:
      - web
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]

  tomcat:
    image: tomcat-cluster
    ports: 
       - 8080
    environment:
      - SERVICE_PORTS=8080
      - HTTP_PORTS=8080
      # - COOKIE=JSESSIONID prefix nocache # prefix nocache
      - COOKIE=SRV insert indirect nocache
      - VIRTUAL_HOST="localhost"
    deploy:
      # mode: global
      replicas: 20
      update_config:
        parallelism: 5
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
      # placement:
      #   constraints:
      #     # - node.labels.type == tomcat
      #     - node.role == worker
    networks: 
      - web

networks: 
  web:
    driver: bridge
