kernel:
  image: linuxkit/kernel:4.14.29
  cmdline: console=ttyS1
  ucode: intel-ucode.cpio
init:
  - linuxkit/init:b212cfeb4bb6330e0a7547d8010fe2e8489b677a
  - linuxkit/runc:7c39a68490a12cde830e1922f171c451fb08e731
  - linuxkit/containerd:37e397ebfc6bd5d8e18695b121166ffd0cbfd9f0
  - linuxkit/ca-certificates:v0.2
  - linuxkit/firmware:v0.2
onboot:
  - name: rngd1
    image: linuxkit/rngd:v0.2
    command: ["/sbin/rngd", "-1"]
  - name: sysctl
    image: linuxkit/sysctl:v0.2
  - name: dhcpcd
    image: linuxkit/dhcpcd:v0.2
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: metadata
    image: linuxkit/metadata:v0.2
    command: ["/usr/bin/metadata", "packet"]
services:
  - name: rngd
    image: linuxkit/rngd:v0.2
  - name: getty
    image: linuxkit/getty:v0.2
    env:
     - INSECURE=true
  - name: sshd
    image: linuxkit/sshd:v0.2
files:
  - path: root/.ssh/authorized_keys
    source: ~/.ssh/id_rsa.pub
    mode: "0600"
    optional: true
trust:
  org:
    - linuxkit
