version: "3.3"

services:

# application
  database:
    build:
      context: ./database
    image: registrationdb
    container_name: registrationdb
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306" 
    networks:
      - back-tier

  webserver:
    build: 
      context: ./appserver
    image: registration
    container_name: webserver
    depends_on:
      - database
    ports:
      - "8080:8080" 
      - "8000:8000"
    networks:
      - front-tier
      - back-tier

  js_client:
    build:
      context: ./signup_client
    image: js_client
    container_name: js_client
    ports:
      - "80:80"
    networks: 
      - front-tier

  messageservice:
    build:
      context: ./messageservice
    image: messageservice
    container_name: messageservice
    depends_on:
      - redis
    ports:
      - "8090:8090"
    networks: 
      - front-tier 
      - back-tier

  worker:
    build:
      context: ./worker
    image: worker
    container_name: worker
    volumes:
      - ./worker/logs:/app/logs
    networks: 
      - back-tier
      - elk

  redis:
    image: redis
    container_name: redis
    ports: 
      - "6379:6379"
    networks:
      - back-tier

#logging
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.2
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks: 
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.1.2
    container_name: kibana
    ports:
      - "5601:5601"
    networks: 
      - elk
    depends_on:
      - elasticsearch

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.1.2
    container_name: logstash
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    ports:
      - "5000:5000"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  front-tier:
  back-tier:
  elk:
 
