version: '3.3'

services:

  web-app:
    image: microsoft/iis:nanoserver
    networks:
      - app-net

  waf:
    image: dockersamples/web-application-firewall:nanoserver
    build:
      context: .
      dockerfile: docker/windows/nanoserver/Dockerfile
    ports:
      - "80"
    depends_on:
      - web-app
    networks:
      - app-net

networks:
  app-net:
    external:
      name: nat