version: '3.1'
services:
    web:
        image: docker-pets:latest
        ports:
            - 80:5000
        healthcheck:
            interval: 10s
            timeout: 2s
            retries: 3  
