version: '3.1'
services:
    web:
        image: chrch/docker-pets:1.0
        deploy:
            mode: replicated
            replicas: 3
            labels:
                com.docker.ucp.mesh.http.5000: "external_route=http://<pets.url>,internal_port=5000"
                com.docker.ucp.mesh.http.7000: "external_route=http://<admin.url>,internal_port=7000,sticky_sessions=paas_admin_id"
        ports:
            - 5000
            - 7000
        healthcheck:
            interval: 10s
            timeout: 2s
            retries: 3

        environment:
            DB: 'db'
            DEBUG: 'False'
            THREADED: 'True'
            ADMIN_PASSWORD_FILE: '/run/secrets/admin_password'

        networks:
            - backend
            - ucp-hrm
        secrets:
            - admin_password
    
    db:
        image: consul:0.7.2
        command: agent -server -ui -client=0.0.0.0 -bootstrap-expect=3 -retry-join=db -retry-join=db -retry-join=db -retry-interval 5s
        deploy:
            replicas: 3
        ports:
            - 8500 
        environment:
            CONSUL_BIND_INTERFACE: 'eth2'
            CONSUL_LOCAL_CONFIG: '{"skip_leave_on_interrupt": true}'
        networks: 
            - backend

    viz:
        image: manomarks/visualizer
        ports:
            - 8080
        deploy:
            placement:
                constraints: [node.role == manager]
            labels:
                com.docker.ucp.mesh.http.8080: "external_route=http://<viz.url>,internal_port=8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks: 
            - ucp-hrm
            
networks:
    backend:
    ucp-hrm:
        external: true

secrets:
    admin_password:
        external: true
