{{/* =% text %= */}}
kind: resource
metadata:
  name: az2-resources
options:
  WaitBeforeProvision: 5
  WaitBeforeDestroy: 5
properties:
  az2-net1:
    plugin: az2/net
    select:
      az: az2
      type: network
    Properties:
      cidr: 10.20.200.0/24
      gateway: 10.20.0.1
  az2-disk0:
    plugin: az2/disk
    select:
      az: az2
      type: storage
    Properties:
      dep: {{ depend `az2-net1/ID` }}
      depname: {{ depend `az2-net1/Tags/infrakit_instance` }}
      gw: {{ depend `az2-net1/Properties/gateway` }}
      fs: ext4
      size: 1TB
  az2-disk1:
    plugin: az2/disk
    select:
      az: az2
      type: storage
    Properties:
      dep: {{ depend `az2-disk0/ID` }}
      depname: {{ depend `az2-disk0/Tags/infrakit_instance` }}
      gw: {{ depend `az2-net1/Properties/gateway` }}
      fs: ext4
      size: 2TB
  az2-disk2:
    plugin: az2/disk
    select:
      az: az2
      type: storage
    Properties:
      dep: {{ depend `az2-disk1/ID` }}
      depname: {{ depend `az2-disk1/Tags/infrakit_instance` }}
      gw: {{ depend `az2-net1/Properties/gateway` }}
      fs: ext4
      size: 3TB
  az2-disk3:
    plugin: az2/disk
    select:
      az: az2
      type: storage
    Properties:
      dep: {{ depend `az2-disk2/ID` }}
      depname: {{ depend `az2-disk2/Tags/infrakit_instance` }}
      gw: {{ depend `az2-net1/Properties/gateway` }}
      fs: ext4
      size: 4TB
  az2-disk4:
    plugin: az2/disk
    select:
      az: az2
      type: storage
    Properties:
      dep: {{ depend `az2-disk3/ID` }}
      depname: {{ depend `az2-disk3/Tags/infrakit_instance` }}
      gw: {{ depend `az2-net1/Properties/gateway` }}
      fs: ext4
      size: 5TB
