version: "3.1"

services: 
  movieplex7:
    build: 
      context: ./movieplex7
    image: movieplex7-tomee
    ports:
      - "8080:8080"
    networks:
      - www
  
  react-client:
    build:
      context: ./react-client
    image: react-client
    ports:
      - "80:80"
    networks:
      - www
  
networks:
    www:
    