{{/* Input to create instance using the AWS instance plugin */}}
{{/* =% instanceProvision `aws/ec2-routetable` %= */}}

{{ $project := param "project" "string" "project" | prompt "Project?" "string" "myproject" }}

{{ $vpcID := param "vpcID" "string" "VPC ID" | prompt "VPC ID?" "string" }}
{{ $gatewayID := param "gatewayID" "string" "Gateway ID" | prompt "Gateway ID?" "string" }}

Tags:
  infrakit_scope: {{ $project }}

Properties:
  Tags:
    Name: {{ $project }}-public-route-via-gateway
  CreateRouteTableInput:
    VpcId : {{ $vpcID }}
  CreateRouteInputs:
    - GatewayId: {{ $gatewayID }}
      DestinationCidrBlock: "0.0.0.0/0"
